version: "3.5"

services:
  web:
    image: ${docker_repo:-kopano-dev}/kopano_web:${KWEB_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "${CADDY:-2015}:2015"
      - "${HTTP:-80}:80"
      - "${HTTPS:-443}:443"
    environment:
      - EMAIL=${EMAIL:-off}
      - FQDN=${FQDNCLEANED?err}
      - DEFAULTREDIRECT=/meet
    command: wrapper.sh
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - web:/.kweb
    networks:
      web-net:
        aliases:
          - ${FQDNCLEANED?err}

  ldap:
    image: ${docker_repo:-kopano-dev}/${LDAP_CONTAINER:-kopano_ldap_demo}:${LDAP_VERSION:-latest}
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}_ldap
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
    command: "--copy-service"
    volumes:
      - ldap:/var/lib/ldap
      - slapd:/etc/ldap/slapd.d
    networks:
      - ldap-net

  kopano_ssl:
    image: ${docker_repo:-kopano-dev}/kopano_ssl:${SSL_VERSION:-latest}
    environment:
      - FQDN=${FQDN}
      - PKI_COUNTRY=NL
    volumes:
      - kopanossl/:/kopano/ssl

  kopano_grapi:
    image: ${docker_repo:-kopano-dev}/kopano_core:${CORE_VERSION:-latest}
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}_grapi
    volumes:
      - kopanosocket/:/run/kopano
    environment:
      - SERVICE_TO_START=grapi
      - TZ=${TZ}
      - ADDITIONAL_KOPANO_PACKAGES=python3-grapi.backend.ldap
      - GRAPI_BACKEND=ldap
      - LDAP_URI=${LDAP_SERVER}
      - LDAP_BINDDN=${LDAP_BIND_DN}
      - LDAP_BINDPW=${LDAP_BIND_PW}
      - LDAP_BASEDN=${LDAP_SEARCH_BASE}
    networks:
      - kopano-net
      - ldap-net

  kopano_kapi:
    image: ${docker_repo:-kopano-dev}/kopano_core:${CORE_VERSION:-latest}
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}_kapi
    depends_on:
      - kopano_grapi
    volumes:
      - kopanodata/:/kopano/data
      - kopanossl/:/kopano/ssl
      - kopanosocket/:/run/kopano
    environment:
      - SERVICE_TO_START=kapi
      - TZ=${TZ}
      - KCCONF_KAPID_LOG_LEVEL=DEBUG
      - KCCONF_KAPID_OIDC_ISSUER_IDENTIFIER=https://${FQDN}
      - KCCONF_KAPID_INSECURE=${INSECURE}
    networks:
      - kopano-net
      - web-net

  kopano_konnect:
    image: ${docker_repo:-kopano-dev}/kopano_konnect:${KONNECT_VERSION:-latest}
    restart: unless-stopped
    command: wrapper.sh
    depends_on:
      - kopano_ssl
      - web
    volumes:
      - kopanossl/:/kopano/ssl
    environment:
      - FQDN=${FQDN}
      - allow_client_guests=yes
      - allow_dynamic_client_registration=yes
      - KONNECT_BACKEND=ldap
      - LDAP_URI=${LDAP_SERVER}
      - LDAP_BINDDN=${LDAP_BIND_DN}
      - LDAP_BINDPW=${LDAP_BIND_PW}
      - LDAP_BASEDN=${LDAP_SEARCH_BASE}
      - LDAP_SCOPE=sub
      - LDAP_LOGIN_ATTRIBUTE=uid
      - LDAP_EMAIL_ATTRIBUTE=mail
      - LDAP_NAME_ATTRIBUTE=cn
      - LDAP_UUID_ATTRIBUTE=uidNumber
      - LDAP_UUID_ATTRIBUTE_TYPE=text
      - LDAP_FILTER=(objectClass=organizationalPerson)
    networks:
      - kopano-net
      - ldap-net
      - web-net

  kopano_kwmserver:
    image: ${docker_repo:-kopano-dev}/kopano_kwmserver:${KWM_VERSION:-latest}
    restart: unless-stopped
    command: wrapper.sh
    depends_on:
      - kopano_kapi
      - kopano_konnect
    environment:
      - INSECURE=${INSECURE}
      - oidc_issuer_identifier=https://${FQDN}
      - enable_guest_api=yes
      - public_guest_access_regexp=^group/public/.*
    volumes:
      - kopanossl/:/kopano/ssl
    networks:
      - web-net

  kopano_meet:
    image: ${docker_repo:-kopano-dev}/kopano_meet:${MEET_VERSION:-latest}
    restart: unless-stopped
    environment:
      - SERVICE_TO_START=meet
      - KCCONF_MEET_disableFullGAB=false
      - KCCONF_MEET_guests_enabled=true
      - KCCONF_MEET_useIdentifiedUser=true
    depends_on:
      - kopano_kapi
      - kopano_konnect
      - kopano_kwmserver
      - web
    networks:
      - web-net

volumes:
  web:
  ldap:
  slapd:
  kopanodata:
  kopanossl:
  kopanosocket:

networks:
  web-net:
  kopano-net:
    driver: bridge
  ldap-net:
    driver: bridge
