sudo: required
dist: bionic
language: node_js

node_js:
  - stable
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce # update to latest docker for buildkit support
  - sudo rm /usr/local/bin/docker-compose # remove pre-installed docker-compose (too old)
  - bash .ci/setup-tools.sh
install:
  - "./version.sh"
  - make lint
  - "./tests/test.exp"
  - "./version.sh"
  - commander test tests/commander.yaml
  - make lint # rerun lint to see if output is different with .env in place
  - echo "docker_repo=$docker_repo" >> .env
  - echo "DOCKERREADME=yes" >> .env # add DOCKERREADME env var so that make publish also updates readme files on docker hub
  - echo "KCCONF_SERVER_SURVEYCLIENT_INTERVAL=0" >> kopano_server.env
  - echo "KOPANO_SURVEYCLIENT_ENABLED=false" >> kopano_konnect.env
  - echo "KOPANO_SURVEYCLIENT_ENABLED=false" >> kopano_kwmserver.env
  - travis_retry make build-all
script:
  - make test-ci
  - docker-compose down -v
  - make test-startup-meet-demo
deploy:
  # login to docker hub
  - provider: script
    skip-cleanup: true
    script: echo "$docker_pwd" | docker login -u "$docker_login" --password-stdin
    on:
      branch: master
  # push images
  - provider: script
    skip-cleanup: true
    script: make publish
    on:
      branch: master
#cache: # uncomment to not load/upload trivy files each time
#  directories:
#    - $HOME/.cache/trivy
