version: "3.5"

services:
  ldap-account-manager:
    image: ldapaccountmanager/lam:7.2 # newer releases may exist
    restart: unless-stopped
    depends_on:
      - ldap
      - web
    volumes:
      - lamconfig/:/var/lib/ldap-account-manager/config
      - lametc/:/etc/ldap-account-manager
      - lamsession/:/var/lib/ldap-account-manager/sess
      - ./ldap-extras/phpldapadmin/templates/creation/create_kopanoCompany.xml:/usr/share/ldap-account-manager/templates/3rdParty/pla/templates/creation/create_kopanoCompany.xml
      - ./ldap-extras/phpldapadmin/templates/creation/create_kopanoUser.xml:/usr/share/ldap-account-manager/templates/3rdParty/pla/templates/creation/create_kopanoUser.xml
      - ./ldap-extras/phpldapadmin/templates/modification/modify_kopanoUser.xml:/usr/share/ldap-account-manager/templates/3rdParty/pla/templates/modification/modify_kopanoUser.xml
    environment:
      - LAM_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LAM_LANG=en_US
      - LAM_TIMEZONE=Europe/Berlin
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - ADMIN_USER=cn=admin,${LDAP_BASE_DN}
      #- DEBUG=true
    networks:
      - ldap-net
      - web-net
volumes:
  lametc:
  lamconfig:
  lamsession:
