version: "3.5"

services:
  kopano_grapi-explorer:
    image: kopano/grapi-explorer
    restart: unless-stopped
    depends_on:
      - kopano_kapi
      - kopano_konnect
    environment:
      - GRAPI_EXPLORER_ISS=https://${FQDN}
      - GRAPI_EXPLORER_GRAPH_URL=https://${FQDN}/api/gc
    networks:
      - kopano-net
      - web-net