version: "3.5"

services:
  kopano_playground:
    image: ${docker_repo:-zokradonh}/kopano_playground
    restart: unless-stopped
    depends_on:
      - kopano_kapi
      - kopano_konnect
    networks:
      - kopano-net
      - web-net