version: "3.5"

services:
  db:
    volumes:
      - ./database/create-additional-databases.sh:/docker-entrypoint-initdb.d/create-additional-databases.sh
    environment:
      - MYSQL_ADDITIONAL_DATABASES=${MYSQL_DATABASE}2

  kopano_server:
    environment:
      - KCCONF_ADMIN_SSLKEY_FILE=/kopano/ssl/admin.pem
      - KCCONF_SERVER_ENABLE_DISTRIBUTED_KOPANO=true
      - KCCONF_SERVER_SERVER_NAME=kopano_server

  kopano_server_2:
    image: ${docker_repo:-zokradonh}/kopano_core:${CORE_VERSION:-latest}
    hostname: kopano_server_2
    container_name: ${COMPOSE_PROJECT_NAME}_server_2
    depends_on:
      - db
      - kopano_konnect
      - kopano_ssl
      - ldap
    environment:
      - ADDITIONAL_KOPANO_PACKAGES=${ADDITIONAL_KOPANO_PACKAGES}
      - KCCOMMENT_LDAP_1=${KCCOMMENT_LDAP_1}
      - KCCONF_ADMIN_SSLKEY_FILE=/kopano/ssl/admin.pem
      - KCCONF_LDAP_LDAP_BIND_PASSWD=${LDAP_BIND_PW}
      - KCCONF_LDAP_LDAP_BIND_USER=${LDAP_BIND_DN}
      - KCCONF_LDAP_LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - KCCONF_LDAP_LDAP_URI=${LDAP_SERVER}
      - KCCONF_SERVER_COREDUMP_ENABLED=no
      - KCCONF_SERVER_ENABLE_DISTRIBUTED_KOPANO=true
      - KCCONF_SERVER_ENABLE_SSO=yes
      - KCCONF_SERVER_KCOIDC_INSECURE_SKIP_VERIFY=${INSECURE}
      - KCCONF_SERVER_KCOIDC_ISSUER_IDENTIFIER=https://${FQDN}
      - KCCONF_SERVER_MYSQL_DATABASE=${MYSQL_DATABASE}2
      - KCCONF_SERVER_MYSQL_HOST=${MYSQL_HOST}
      - KCCONF_SERVER_MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KCCONF_SERVER_MYSQL_PORT=3306
      - KCCONF_SERVER_MYSQL_USER=${MYSQL_USER}
      - KCCONF_SERVER_PROXY_HEADER=* # delete line if webapp is not behind reverse proxy
      - KCCONF_SERVER_SERVER_NAME=kopano_server_2
      - KCCONF_SERVER_SERVER_SSL_CA_FILE=/kopano/ssl/ca.pem
      - KCCONF_SERVER_SERVER_SSL_KEY_FILE=/kopano/ssl/kopano_server_2.pem
      - KCCONF_SERVER_SSLKEYS_PATH=/kopano/ssl/clients
      - KCCONF_SERVER_SYSTEM_EMAIL_ADDRESS=${POSTMASTER_ADDRESS}
      - KCUNCOMMENT_LDAP_1=${KCUNCOMMENT_LDAP_1}
      - SERVICE_TO_START=server
      - TZ=${TZ}
    env_file:
      - kopano_server.env
    networks:
      - kopano-net
      - ldap-net
      - web-net
    volumes:
      - /etc/machine-id:/etc/machine-id
      - /etc/machine-id:/var/lib/dbus/machine-id
      - kopanodata2/:/kopano/data
      - kopanosocket2/:/run/kopano
      - kopanossl/:/kopano/ssl

  kopano_spooler_2:
    image: ${docker_repo:-zokradonh}/kopano_core:${CORE_VERSION:-latest}
    restart: unless-stopped
    hostname: spooler_2
    container_name: ${COMPOSE_PROJECT_NAME}_spooler_2
    domainname: ${LDAP_DOMAIN}
    depends_on:
      - kopano_server_2
      - mail
    volumes:
      - kopanosocket2/:/run/kopano
      - kopanossl/:/kopano/ssl
    environment:
      - KCCONF_SPOOLER_LOG_LEVEL=3
      - KCCONF_SPOOLER_SMTP_SERVER=mail
      - KCCONF_SPOOLER_SSLKEY_FILE=/kopano/ssl/kopano_spooler.pem
      - SERVICE_TO_START=spooler
      - TZ=${TZ}
    env_file:
      - kopano_spooler.env
    networks:
      - kopano-net

  kopano_scheduler:
    depends_on:
      - kopano_server_2
    environment:
      - CRON_KOPANOUSERS2=10 * * * * docker exec kopano_server_2 kopano-admin --sync

volumes:
  kopanodata2:
  kopanosocket2:
